# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dieuhoa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import buttonn

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 797)
        MainWindow.setStyleSheet("background-color: rgb(17, 17, 17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 50, 71, 181))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setTabletTracking(False)
        self.pushButton_3.setStyleSheet("border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("living room.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_3.setShortcut("")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 620, 70, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("QCheckBox::indicator:checked{    \n"
"    \n"
"    image: url(:/newPrefix/lanhoff.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/lanhon.png);\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(180, 620, 70, 100))
        self.checkBox_3.setStyleSheet("QCheckBox::indicator:checked{    \n"
"    \n"
"    image: url(:/newPrefix/quatoff1.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/quaton.png);\n"
"\n"
"}")
        self.checkBox_3.setText("")
        self.checkBox_3.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 620, 70, 100))
        self.checkBox_4.setStyleSheet("QCheckBox::indicator:checked{    \n"
"    \n"
"    image: url(:/newPrefix/giooff.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/gioon.png);\n"
"\n"
"}")
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 60, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(15, 15,15);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 40, 40))
        self.label_3.setStyleSheet("border-radius: 39px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 215, 55, 16))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(354, 5, 31, 31))
        self.label_6.setStyleSheet("background-color: rgb(17, 17, 17);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.circularProgressBar_Main = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBar_Main.setGeometry(QtCore.QRect(120, 280, 240, 240))
        self.circularProgressBar_Main.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main.setObjectName("circularProgressBar_Main")
        self.circularProgressCPU_2 = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularProgressCPU_2.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularProgressCPU_2.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.circularProgressCPU_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU_2.setObjectName("circularProgressCPU_2")
        self.circularBg_2 = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularBg_2.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularBg_2.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg_2.setObjectName("circularBg_2")
        self.circularContainer_2 = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularContainer_2.setGeometry(QtCore.QRect(25, 25, 190, 190))
        self.circularContainer_2.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_2.setStyleSheet("QFrame{\n"
"    border-radius: 95px;    \n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.circularContainer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_2.setObjectName("circularContainer_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.circularContainer_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 171, 156))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.infoLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.infoLayout_2.setContentsMargins(0, 0, 0, 0)
        self.infoLayout_2.setObjectName("infoLayout_2")
        self.labelAplicationName_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelAplicationName_2.setFont(font)
        self.labelAplicationName_2.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.labelAplicationName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAplicationName_2.setObjectName("labelAplicationName_2")
        self.infoLayout_2.addWidget(self.labelAplicationName_2, 0, 0, 1, 1)
        self.labelPercentageCPU_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.labelPercentageCPU_2.setFont(font)
        self.labelPercentageCPU_2.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.labelPercentageCPU_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentageCPU_2.setIndent(-1)
        self.labelPercentageCPU_2.setObjectName("labelPercentageCPU_2")
        self.infoLayout_2.addWidget(self.labelPercentageCPU_2, 2, 0, 1, 1)
        self.labelCredits_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.labelCredits_2.setFont(font)
        self.labelCredits_2.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.labelCredits_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCredits_2.setObjectName("labelCredits_2")
        self.infoLayout_2.addWidget(self.labelCredits_2, 3, 0, 1, 1)
        self.sliderCPU = QtWidgets.QSlider(self.centralwidget)
        self.sliderCPU.setGeometry(QtCore.QRect(160, 540, 161, 22))
        self.sliderCPU.setStyleSheet("/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}")
        self.sliderCPU.setMaximum(100)
        self.sliderCPU.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCPU.setObjectName("sliderCPU")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(367, 10, 17, 17))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_maximize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_maximize.setGeometry(QtCore.QRect(313, 10, 17, 17))
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(340, 10, 17, 17))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 61, 821))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(300, 179, 81, 41))
        self.checkBox.setStyleSheet("QCheckBox::indicator:checked{    \n"
"    \n"
"    image: url(:/newPrefix/off2.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/on2.png);\n"
"\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "   AIR\n"
"  CONDITIONER"))
        self.labelAplicationName_2.setText(_translate("MainWindow", "<html><head/><body><p>Nhiet Do</p></body></html>"))
        self.labelPercentageCPU_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#ff5500;\">28°</span></p></body></html>"))
        self.labelCredits_2.setText(_translate("MainWindow", "<html><head/><body><p>MAX: <span style=\" color:#ffffff;\">40º</span></p></body></html>"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.label.setText(_translate("MainWindow", "TextLabel"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
